### ISSUE TITLE
Issue in linking Openssl1.1.1b to application

### ISSUE THREAD

**Issue by vinayashreeks** [stardock/openssl1.1.1#1]
Hi 

I was using an application with openssl0.9.8k .The procedure i used to link 
openssl to my application using visual studio -2008 was after building 
openssl i was linking libeay32.lib and ssleay32.lib to my application and 
including header files from include folder. 

Now with openssl1.1.1b ,after building openssl I am linking openssl.lib 
,libcrypto.lib and libssl.lib to my application and including header 
files.Building application using visual studio 2008 .And when i try to 
register that built dll in windows 7 32 bit machine ,its giving error as 
"RegSvr32 : The module XXX.dll failed to load.  Make sure the binary is 
stored at the specified path or debug it to check for problems with the 
binary or dependent .DLL files.The specified module could not be found. 
"   

Can anyone please tell me whether the library linking is enough or any dll 
linking needs to be done?? 
Any step i am missing please let me know? 

Thanks in advance

**Comment by stardock** [comment]
Hi,

The only purpose for this new version of openssl is the tls v1.3 support.
We strongly suggest you use the original one if it's working for you.

new features: https://www.oschina.net/news/99864/openssl-1-1-1-released
difference: https://blog.csdn.net/antony1776/article/details/82801549
